// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<SystemStats> getSystemStats() =>
    RustLib.instance.api.crateApiSimpleGetSystemStats();

class SystemStats {
  final BigInt totalMemory;
  final BigInt usedMemory;
  final BigInt freeMemory;
  final double memoryUsagePercent;
  final double cpuUsage;
  final String? systemName;
  final String? kernelVersion;
  final String? osVersion;
  final String? hostName;
  final BigInt totalSwap;
  final BigInt usedSwap;

  const SystemStats({
    required this.totalMemory,
    required this.usedMemory,
    required this.freeMemory,
    required this.memoryUsagePercent,
    required this.cpuUsage,
    this.systemName,
    this.kernelVersion,
    this.osVersion,
    this.hostName,
    required this.totalSwap,
    required this.usedSwap,
  });

  @override
  int get hashCode =>
      totalMemory.hashCode ^
      usedMemory.hashCode ^
      freeMemory.hashCode ^
      memoryUsagePercent.hashCode ^
      cpuUsage.hashCode ^
      systemName.hashCode ^
      kernelVersion.hashCode ^
      osVersion.hashCode ^
      hostName.hashCode ^
      totalSwap.hashCode ^
      usedSwap.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemStats &&
          runtimeType == other.runtimeType &&
          totalMemory == other.totalMemory &&
          usedMemory == other.usedMemory &&
          freeMemory == other.freeMemory &&
          memoryUsagePercent == other.memoryUsagePercent &&
          cpuUsage == other.cpuUsage &&
          systemName == other.systemName &&
          kernelVersion == other.kernelVersion &&
          osVersion == other.osVersion &&
          hostName == other.hostName &&
          totalSwap == other.totalSwap &&
          usedSwap == other.usedSwap;
}
